<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'ConduitAPI_differential_getcommitdata_Method' => 'conduit/ConduitAPI_differential_getcommitdata_Method.php',
    'ExtendedIRCDifferentialNotificationHandler' => 'ircbot/ExtendedIRCDifferentialNotificationHandler.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'ConduitAPI_differential_getcommitdata_Method' => 'ConduitAPIMethod',
    'ExtendedIRCDifferentialNotificationHandler' => 'PhabricatorIRCHandler',
  ),
));
