<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'DifferentialGetCommitDataConduitAPIMethod' => 'conduit/DifferentialGetCommitDataConduitAPIMethod.php',
    'ExtendedIRCDifferentialNotificationHandler' => 'ircbot/ExtendedIRCDifferentialNotificationHandler.php',
    'INdTNotificationHandler' => 'ircbot/INdTNotificationHandler.php',
    'PhabricatorApplicationSendmail' => 'sendmail/application/PhabricatorApplicationSendmail.php',
    'SendmailController' => 'sendmail/controller/SendmailController.php',
  ),
  'function' => array(),
  'xmap' => array(
    'DifferentialGetCommitDataConduitAPIMethod' => 'ConduitAPIMethod',
    'ExtendedIRCDifferentialNotificationHandler' => 'PhabricatorBotHandler',
    'INdTNotificationHandler' => 'ExtendedIRCDifferentialNotificationHandler',
    'PhabricatorApplicationSendmail' => 'PhabricatorApplication',
    'SendmailController' => 'PhabricatorController',
  ),
));
